export default [
  {
    company_name: "BK Brokers",
    monthly_revenu: 738,
    expert_review: true,
    expert_review_status: "active",
    licenses: 5,
    payment_due: "15 May 21",
    isActive: true,
  },
  {
    company_name: "Kantam Finances",
    monthly_revenu: 338,
    expert_review: false,
    expert_review_status: "NA",
    isActive: true,
    licenses: 1,
    payment_due: "15 May 21",
  },
  {
    company_name: "Reta Securities",
    monthly_revenu: 738,
    expert_review: false,
    expert_review_status: "NA",
    licenses: 5,
    payment_due: "15 May 21",
    isActive: true,
  },
  {
    company_name: "Millenium Brokers",
    monthly_revenu: 738,
    expert_review: true,
    expert_review_status: "paused",
    licenses: 4,
    payment_due: "15 May 21",
    isActive: true,
  },
  {
    company_name: "Yware Technologies",
    monthly_revenu: 738,
    expert_review: true,
    expert_review_status: "inactive",
    licenses: 7,
    payment_due: "15 May 21",
    isActive: true,
  },
];
