export const GET_PAYMENT_DETAIL = "GET_PAYMENT_DETAIL";
export const SET_PAYMENT_DETAIL = "SET_PAYMENT_DETAIL";
export const MAKE_PAYMENT = "MAKE_PAYMENT";
export const SET_SUCCESS = "SET_SUCCESS";
export const IS_PAYMENT_DONE = "IS_PAYMENT_DONE";
