export default [
  {
    Status: "overdue",
    ORD: 1,
    Details: [
      {
        Cnt: 6,
        LicenseCode: "NSDL",
        TaskName: "Risk Assessment Template",
        Status: "Assigned",
        EntityName: "Dell Technologies LLC",
        AssignedName: "Prithvi Raj Chauhan",
        ApproverName: "Alpha APP",
        AssignedTo: 229,
        AssignedToApprover: 278,
        EndDate: "31 Jul 2021",
        TaskId: 7857,
      },
      {
        Cnt: 6,
        LicenseCode: "GST",
        TaskName: "Filing of GSTR-1",
        Status: "Assigned",
        EntityName: "Mains",
        AssignedName: "John Doe",
        ApproverName: "Alpha APP",
        AssignedTo: 227,
        AssignedToApprover: 278,
        EndDate: "10 Aug 2021",
        TaskId: 9936,
      },
      {
        Cnt: 6,
        LicenseCode: "NSDL",
        TaskName: "Investor grievance report",
        Status: "Assigned",
        EntityName: "Dell Technologies LLC",
        AssignedName: "Monica Rajput",
        ApproverName: "Ashu Kumar",
        AssignedTo: 225,
        AssignedToApprover: 215,
        EndDate: "10 Aug 2021",
        TaskId: 7853,
      },
    ],
  },
  {
    Status: "Pending",
    ORD: 2,
    Details: [
      {
        LicenseCode: "Norec",
        TaskName: "Norec",
        Status: "Norec",
        EntityName: "Norec",
        AssignedName: "Assign",
        ApproverName: "Assign",
        AssignedTo: 0,
        AssignedToApprover: 0,
        EndDate: "11 Aug 2021",
        TaskId: 0,
      },
    ],
  },
  {
    Status: "Upcoming",
    ORD: 3,
    Details: [
      {
        Cnt: 13,
        LicenseCode: "GST",
        TaskName: "Filing of GSTR-3B monthly return",
        Status: "Assign",
        EntityName: "Mains",
        AssignedName: "Assign",
        ApproverName: "Assign",
        AssignedTo: 0,
        AssignedToApprover: 0,
        EndDate: "20 Aug 2021",
        TaskId: 9937,
      },
      {
        Cnt: 13,
        LicenseCode: "GST",
        TaskName: "Payment of GST",
        Status: "Assign",
        EntityName: "Mains",
        AssignedName: "Assign",
        ApproverName: "Assign",
        AssignedTo: 0,
        AssignedToApprover: 0,
        EndDate: "20 Aug 2021",
        TaskId: 9938,
      },
      {
        Cnt: 13,
        LicenseCode: "IT",
        TaskName: "Payment of TDS",
        Status: "Assign",
        EntityName: "Mains",
        AssignedName: "Assign",
        ApproverName: "Assign",
        AssignedTo: 0,
        AssignedToApprover: 0,
        EndDate: "30 Aug 2021",
        TaskId: 9940,
      },
      {
        Cnt: 13,
        LicenseCode: "NSDL",
        TaskName: "Transaction statement",
        Status: "Assigned",
        EntityName: "Dell Technologies LLC",
        AssignedName: "Prithvi Raj Chauhan",
        ApproverName: "Alpha APP",
        AssignedTo: 229,
        AssignedToApprover: 278,
        EndDate: "30 Aug 2021",
        TaskId: 9912,
      },
      {
        Cnt: 13,
        LicenseCode: "IT",
        TaskName: "Payment of TDS",
        Status: "Assigned",
        EntityName: "Mains",
        AssignedName: "John Doe",
        ApproverName: "Ashu Kumar",
        AssignedTo: 227,
        AssignedToApprover: 215,
        EndDate: "07 Sep 2021",
        TaskId: 11624,
      },
      {
        Cnt: 13,
        LicenseCode: "IT",
        TaskName: "Payment of Advance Tax",
        Status: "Assign",
        EntityName: "Mains",
        AssignedName: "Assign",
        ApproverName: "Assign",
        AssignedTo: 0,
        AssignedToApprover: 0,
        EndDate: "15 Sep 2021",
        TaskId: 9943,
      },
      {
        Cnt: 13,
        LicenseCode: "IT",
        TaskName: "Tax Audit Report",
        Status: "Assign",
        EntityName: "Mains",
        AssignedName: "Assign",
        ApproverName: "Assign",
        AssignedTo: 0,
        AssignedToApprover: 0,
        EndDate: "30 Sep 2021",
        TaskId: 9946,
      },
      {
        Cnt: 13,
        LicenseCode: "IT",
        TaskName: "IT Return",
        Status: "Assign",
        EntityName: "Mains",
        AssignedName: "Assign",
        ApproverName: "Assign",
        AssignedTo: 0,
        AssignedToApprover: 0,
        EndDate: "30 Sep 2021",
        TaskId: 9945,
      },
      {
        Cnt: 13,
        LicenseCode: "IT",
        TaskName: "Filing TDS Return",
        Status: "Assign",
        EntityName: "Mains",
        AssignedName: "Assign",
        ApproverName: "Assign",
        AssignedTo: 0,
        AssignedToApprover: 0,
        EndDate: "30 Oct 2021",
        TaskId: 9942,
      },
      {
        Cnt: 13,
        LicenseCode: "NSDL",
        TaskName: "Internal audit report (IAR)",
        Status: "Assign",
        EntityName: "Dell Technologies LLC",
        AssignedName: "Assign",
        ApproverName: "Assign",
        AssignedTo: 0,
        AssignedToApprover: 0,
        EndDate: "15 Nov 2021",
        TaskId: 7856,
      },
      {
        Cnt: 13,
        LicenseCode: "GST",
        TaskName: "Filing of GSTR-9 & GSTR-9C Annual Return",
        Status: "Assign",
        EntityName: "Mains",
        AssignedName: "Assign",
        ApproverName: "Assign",
        AssignedTo: 0,
        AssignedToApprover: 0,
        EndDate: "30 Dec 2021",
        TaskId: 9939,
      },
      {
        Cnt: 13,
        LicenseCode: "NSDL",
        TaskName: "Half yearly compliance certificate",
        Status: "Assigned",
        EntityName: "Dell Technologies LLC",
        AssignedName: "John Doe",
        ApproverName: "Alpha APP",
        AssignedTo: 227,
        AssignedToApprover: 278,
        EndDate: "30 Jan 2022",
        TaskId: 8028,
      },
      {
        Cnt: 13,
        LicenseCode: "NSDL",
        TaskName: "Risk Assessment Template",
        Status: "Assigned",
        EntityName: "Dell Technologies LLC",
        AssignedName: "Prithvi Raj Chauhan",
        ApproverName: "Alpha APP",
        AssignedTo: 229,
        AssignedToApprover: 278,
        EndDate: "31 Jan 2022",
        TaskId: 11467,
      },
      {
        Cnt: 13,
        LicenseCode: "NSDL",
        TaskName: "Submission of tariff structure",
        Status: "Assign",
        EntityName: "Dell Technologies LLC",
        AssignedName: "Assign",
        ApproverName: "Assign",
        AssignedTo: 0,
        AssignedToApprover: 0,
        EndDate: "30 Apr 2022",
        TaskId: 7860,
      },
      {
        Cnt: 13,
        LicenseCode: "NSDL",
        TaskName:
          "Annual System audit report on cyber security & cyber resilience framework for DP & Type I & II Stock Broker.",
        Status: "Assign",
        EntityName: "Dell Technologies LLC",
        AssignedName: "Assign",
        ApproverName: "Assign",
        AssignedTo: 0,
        AssignedToApprover: 0,
        EndDate: "30 Jun 2022",
        TaskId: 7858,
      },
      {
        Cnt: 13,
        LicenseCode: "IT",
        TaskName:
          "Filing of IT Return (Non corporate & non tax audit assessees)",
        Status: "Assign",
        EntityName: "Mains",
        AssignedName: "Assign",
        ApproverName: "Assign",
        AssignedTo: 0,
        AssignedToApprover: 0,
        EndDate: "30 Jul 2022",
        TaskId: 9944,
      },
      {
        Cnt: 13,
        LicenseCode: "NSDL",
        TaskName:
          "Networth certificate & annual financial statement submission",
        Status: "Assigned",
        EntityName: "Dell Technologies LLC",
        AssignedName: "Jonh",
        ApproverName: "Ashu Kumar",
        AssignedTo: 237,
        AssignedToApprover: 215,
        EndDate: "30 Sep 2022",
        TaskId: 9913,
      },
    ],
  },
  {
    Status: "Completed",
    ORD: 4,
    Details: [
      {
        Cnt: 0,
        LicenseCode: "NSDL",
        TaskName: "Transaction statement",
        Status: "Approved",
        EntityName: "Dell Technologies LLC",
        AssignedName: "Prithvi Raj Chauhan",
        ApproverName: "Alpha APP",
        AssignedTo: 229,
        AssignedToApprover: 278,
        EndDate: "30 Jul 2021",
        TaskId: 7854,
      },
      {
        Cnt: 0,
        LicenseCode: "NSDL",
        TaskName: "Half yearly compliance certificate",
        Status: "Approved",
        EntityName: "Dell Technologies LLC",
        AssignedName: "John Doe",
        ApproverName: "Alpha APP",
        AssignedTo: 227,
        AssignedToApprover: 278,
        EndDate: "30 Jul 2021",
        TaskId: 7855,
      },
      {
        Cnt: 0,
        LicenseCode: "IT",
        TaskName: "Payment of TDS",
        Status: "Approved",
        EntityName: "Mains",
        AssignedName: "John Doe",
        ApproverName: "Ashu Kumar",
        AssignedTo: 227,
        AssignedToApprover: 215,
        EndDate: "07 Aug 2021",
        TaskId: 9941,
      },
      {
        Cnt: 0,
        LicenseCode: "NSDL",
        TaskName:
          "Networth certificate & annual financial statement submission",
        Status: "Approved",
        EntityName: "Dell Technologies LLC",
        AssignedName: "Jonh",
        ApproverName: "Ashu Kumar",
        AssignedTo: 237,
        AssignedToApprover: 215,
        EndDate: "30 Sep 2021",
        TaskId: 7859,
      },
    ],
  },
];
