export const GET_REASSIGN_TASKS_LIST = "GET_REASSIGN_TASKS_LIST";
export const SET_REASSIGN_TASKS_LIST = "SET_REASSIGN_TASKS_LIST";
export const SET_LOADING = "SET_LOADING";
export const SET_SUCCESS = "SET_SUCCESS";
export const SELECT_FROM_DATE = "SELECT_FROM_DATE";
export const SELECT_TO_DATE = "SELECT_TO_DATE";
export const CLEAR_STATE = "CLEAR_STATE";
export const API_ERROR = "API_ERROR";
