export default {
  Status: "NSDL",
  ORD: 53195,
  Details: [
    {
      Cnt: 0,
      LicenseCode: "NSDL",
      TaskName: "Half yearly compliance certificate",
      Status: "Approved",
      EntityName: "Dell Technologies LLC",
      AssignedName: "John Doe",
      ApproverName: "Alpha APP",
      AssignedTo: 227,
      AssignedToApprover: 278,
      EndDate: "30 Jul 2021",
      TaskId: 7855,
    },
    {
      Cnt: 0,
      LicenseCode: "NSDL",
      TaskName: "Transaction statement",
      Status: "Approved",
      EntityName: "Dell Technologies LLC",
      AssignedName: "Prithvi Raj Chauhan",
      ApproverName: "Alpha APP",
      AssignedTo: 229,
      AssignedToApprover: 278,
      EndDate: "30 Jul 2021",
      TaskId: 7854,
    },
    {
      Cnt: 6,
      LicenseCode: "NSDL",
      TaskName: "Risk Assessment Template",
      Status: "Assigned",
      EntityName: "Dell Technologies LLC",
      AssignedName: "Prithvi Raj Chauhan",
      ApproverName: "Alpha APP",
      AssignedTo: 229,
      AssignedToApprover: 278,
      EndDate: "31 Jul 2021",
      TaskId: 7857,
    },
    {
      Cnt: 6,
      LicenseCode: "NSDL",
      TaskName: "Investor grievance report",
      Status: "Assigned",
      EntityName: "Dell Technologies LLC",
      AssignedName: "Monica Rajput",
      ApproverName: "Ashu Kumar",
      AssignedTo: 225,
      AssignedToApprover: 215,
      EndDate: "10 Aug 2021",
      TaskId: 7853,
    },
    {
      Cnt: 13,
      LicenseCode: "NSDL",
      TaskName: "Transaction statement",
      Status: "Assigned",
      EntityName: "Dell Technologies LLC",
      AssignedName: "Prithvi Raj Chauhan",
      ApproverName: "Alpha APP",
      AssignedTo: 229,
      AssignedToApprover: 278,
      EndDate: "30 Aug 2021",
      TaskId: 9912,
    },
    {
      Cnt: 0,
      LicenseCode: "NSDL",
      TaskName: "Networth certificate & annual financial statement submission",
      Status: "Approved",
      EntityName: "Dell Technologies LLC",
      AssignedName: "Jonh",
      ApproverName: "Ashu Kumar",
      AssignedTo: 237,
      AssignedToApprover: 215,
      EndDate: "30 Sep 2021",
      TaskId: 7859,
    },
    {
      Cnt: 13,
      LicenseCode: "NSDL",
      TaskName: "Internal audit report (IAR)",
      Status: "Assign",
      EntityName: "Dell Technologies LLC",
      AssignedName: "Assign",
      ApproverName: "Assign",
      AssignedTo: 0,
      AssignedToApprover: 0,
      EndDate: "15 Nov 2021",
      TaskId: 7856,
    },
    {
      Cnt: 13,
      LicenseCode: "NSDL",
      TaskName: "Half yearly compliance certificate",
      Status: "Assigned",
      EntityName: "Dell Technologies LLC",
      AssignedName: "John Doe",
      ApproverName: "Alpha APP",
      AssignedTo: 227,
      AssignedToApprover: 278,
      EndDate: "30 Jan 2022",
      TaskId: 8028,
    },
    {
      Cnt: 13,
      LicenseCode: "NSDL",
      TaskName: "Risk Assessment Template",
      Status: "Assigned",
      EntityName: "Dell Technologies LLC",
      AssignedName: "Prithvi Raj Chauhan",
      ApproverName: "Alpha APP",
      AssignedTo: 229,
      AssignedToApprover: 278,
      EndDate: "31 Jan 2022",
      TaskId: 11467,
    },
    {
      Cnt: 13,
      LicenseCode: "NSDL",
      TaskName: "Submission of tariff structure",
      Status: "Assign",
      EntityName: "Dell Technologies LLC",
      AssignedName: "Assign",
      ApproverName: "Assign",
      AssignedTo: 0,
      AssignedToApprover: 0,
      EndDate: "30 Apr 2022",
      TaskId: 7860,
    },
    {
      Cnt: 13,
      LicenseCode: "NSDL",
      TaskName:
        "Annual System audit report on cyber security & cyber resilience framework for DP & Type I & II Stock Broker.",
      Status: "Assign",
      EntityName: "Dell Technologies LLC",
      AssignedName: "Assign",
      ApproverName: "Assign",
      AssignedTo: 0,
      AssignedToApprover: 0,
      EndDate: "30 Jun 2022",
      TaskId: 7858,
    },
    {
      Cnt: 13,
      LicenseCode: "NSDL",
      TaskName: "Networth certificate & annual financial statement submission",
      Status: "Assigned",
      EntityName: "Dell Technologies LLC",
      AssignedName: "Jonh",
      ApproverName: "Ashu Kumar",
      AssignedTo: 237,
      AssignedToApprover: 215,
      EndDate: "30 Sep 2022",
      TaskId: 9913,
    },
  ],
};
