export const ADD_NEW_SECTION = "ADD_NEW_SECTION";
export const SET_SECTION_NAME = "SET_SECTION_NAME";
export const GET_SECTION_NAME = "GET_SECTION_NAME";

export const SET_TEMPLATE_NAME = "SET_TEMPLATE_NAME";
export const GET_TEMPLATE_NAME = "GET_TEMPLATE_NAME";

export const SET_QUESTION_LIST = "SET_QUESTION_LIST";
export const GET_QUESTION_LIST = "GET_QUESTION_LIST";

export const SET_AUDIT_ASSIGNMENT_BASIC_DETAILS = "SET_AUDIT_ASSIGNMENT_BASIC_DETAILS";
export const GET_AUDIT_ASSIGNMENT_BASIC_DETAILS = "GET_AUDIT_ASSIGNMENT_BASIC_DETAILS";

export const SET_ASSIGNMENT_ID = "SET_ASSIGNMENT_ID";