export const ADD_NEW_SECTION = "ADD_NEW_SECTION";
export const SET_SECTION_NAME = "SET_SECTION_NAME";
export const GET_SECTION_NAME = "GET_SECTION_NAME";
export const SET_QUESTION_LIST = "SET_QUESTION_LIST";
export const GET_QUESTION_LIST = "GET_QUESTION_LIST";
