export const ADD_NEW_SECTION = "ADD_NEW_SECTION";
export const SET_SECTION_NAME = "SET_SECTION_NAME";
export const GET_SECTION_NAME = "GET_SECTION_NAME";
export const SET_TEMPLATE_NAME = "SET_TEMPLATE_NAME";
export const GET_TEMPLATE_NAME = "GET_TEMPLATE_NAME";

