import moment from 'moment';
export const events = [
    {
        "Cnt": 11,
        "LicenseCode": "PF",
        "title": "Filing PF return",
        "Status": "Assign",
        "EntityName": "Infobiz",
        "AssignedName": "Assign",
        "ApproverName": "Assign",
        "AssignedTo": 0,
        "AssignedToApprover": 0,
        "date": moment("25 May 2021").format('YYYY-MM-DD'),
        "TaskId": 710497
    },
    {
        "Cnt": 11,
        "LicenseCode": "AIF",
        "title": "Quarterly Report to AIF III investor",
        "Status": "Assigned",
        "EntityName": "Infobiz",
        "AssignedName": "test@gmail.com",
        "ApproverName": "Assign",
        "AssignedTo": 29373,
        "AssignedToApprover": 0,
        "date": moment("28 May 2021").format('YYYY-MM-DD'),
        "TaskId": 710528
    },
    {
        "Cnt": 11,
        "LicenseCode": "PMS",
        "title": "Annual Audited firm-level performance data",
        "Status": "Assign",
        "EntityName": "Infobiz",
        "AssignedName": "Assign",
        "ApproverName": "Assign",
        "AssignedTo": 0,
        "AssignedToApprover": 0,
        "date": moment("30 May 2021").format('YYYY-MM-DD'),
        "TaskId": 710554
    },
    {
        "Cnt": 11,
        "LicenseCode": "PMS",
        "title": "Annual Certificate of compliance for SEBI Regulation",
        "Status": "Assign",
        "EntityName": "Infobiz",
        "AssignedName": "Assign",
        "ApproverName": "Assign",
        "AssignedTo": 0,
        "AssignedToApprover": 0,
        "date": moment("30 May 2021").format('YYYY-MM-DD'),
        "TaskId": 710555
    },
    {
        "Cnt": 11,
        "LicenseCode": "PMS",
        "title": "Annual Compliance with reporting of Performance",
        "Status": "Assign",
        "EntityName": "Infobiz",
        "AssignedName": "Assign",
        "ApproverName": "Assign",
        "AssignedTo": 0,
        "AssignedToApprover": 0,
        "date": moment("30 May 2021").format('YYYY-MM-DD'),
        "TaskId": 710557
    },
    {
        "Cnt": 11,
        "LicenseCode": "IT",
        "title": "Payment of TDS",
        "Status": "Assign",
        "EntityName": "Infobiz",
        "AssignedName": "Assign",
        "ApproverName": "Assign",
        "AssignedTo": 0,
        "AssignedToApprover": 0,
        "date": moment("30 May 2021").format('YYYY-MM-DD'),
        "TaskId": 710518
    },
    {
        "Cnt": 11,
        "LicenseCode": "ROC",
        "title": "LLP - Form-11 Annual Return ( within 60 days of end of FY)",
        "Status": "Assign",
        "EntityName": "Infobiz",
        "AssignedName": "Assign",
        "ApproverName": "Assign",
        "AssignedTo": 0,
        "AssignedToApprover": 0,
        "date": moment("30 May 2021").format('YYYY-MM-DD'),
        "TaskId": 710508
    },
    {
        "Cnt": 11,
        "LicenseCode": "ROC",
        "title": "ROC",
        "Status": "Assign",
        "EntityName": "Infobiz",
        "AssignedName": "Assign",
        "ApproverName": "Assign",
        "AssignedTo": 0,
        "AssignedToApprover": 0,
        "date": moment("31 May 2021").format('YYYY-MM-DD'),
        "TaskId": 710511
    },
    {
        "Cnt": 11,
        "LicenseCode": "ROC",
        "title": "ROC)",
        "Status": "Assign",
        "EntityName": "Infobiz",
        "AssignedName": "Assign",
        "ApproverName": "Assign",
        "AssignedTo": 0,
        "AssignedToApprover": 0,
        "date": moment("31 May 2021").format('YYYY-MM-DD'),
        "TaskId": 710512
    },
    {
        "Cnt": 11,
        "LicenseCode": "AIF",
        "title": "AIF",
        "Status": "Assign",
        "EntityName": "Infobiz",
        "AssignedName": "Assign",
        "ApproverName": "Assign",
        "AssignedTo": 0,
        "AssignedToApprover": 0,
        "date": moment("31 May 2021").format('YYYY-MM-DD'),
        "TaskId": 710526
    },
    {
        "Cnt": 11,
        "LicenseCode": "PT",
        "title": "PT",
        "Status": "Assign",
        "EntityName": "Infobiz",
        "AssignedName": "Assign",
        "ApproverName": "Assign",
        "AssignedTo": 0,
        "AssignedToApprover": 0,
        "date": moment("31 May 2021").format('YYYY-MM-DD'),
        "TaskId": 710500
    }
]